/*
 *
 * Task code generated by SAS Studio 3.8 
 *
 * Generated on '10/6/23, 2:42 PM' 
 * Generated by 'SRIHARI' 
 * Generated on server 'DESKTOP-IQR8VSG.UCONN.EDU' 
 * Generated on SAS platform 'X64_10HOME WIN' 
 * Generated on SAS version '9.04.01M6P11152018' 
 * Generated on browser 'Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:109.0) Gecko/20100101 Firefox/118.0' 
 * Generated on web client 'http://localhost:59904/main?locale=en_US&zone=GMT-04%253A00&sutoken=%257BFB9935E4-6C47-4C38-9048-5359D32C0E23%257D' 
 *
 */

ods noproctitle;
ods graphics / imagemap=on;

proc sort data=STSM.SOLARPROJPREP out=Work.preProcessedData;
	by DATE_TIME;
run;

proc arima data=Work.preProcessedData plots
     (only)=(series(corr crosscorr) residual(corr normal) 
		forecast(forecast) );
	identify var='Wind Speed(mph)'n(1 1);
	estimate p=(1 2 3 4 5 6 7 8 9 10 11 12) q=(1 2 3 4 5 6 7 8 9 10 11 12) 
		method=ML;
	identify var=AC_POWER crosscorr=('Wind Speed(mph)'n);
	estimate input=('Wind Speed(mph)'n) method=ML;
	run;
quit;

proc delete data=Work.preProcessedData;
run;